[tool]
[tool.poetry]
authors = ["b-van-b"]
name = "root"
version = "0.0.0"
description = ""

[tool.poetry.dependencies]
pandas = "*"
python = "^3.8"
seaborn = "*"
matplotlib = "^3.6.2"
numpy = "^1.23.4"
